export const events = [
  {
    slug: "year-end-ai-meetup-2025",
    image: "/images/event6.png",
    title: "Year‑End AI Meetup",
    location: "Online",
    date: "December 16, 2025",
    time: "6:00 PM - 8:30 PM",
  },
  {
    slug: "winter-hackathon-2025",
    image: "/images/event2.png",
    title: "Global Winter Hackathon",
    location: "Online",
    date: "December 28-30, 2025",
    time: "48 Hours",
  },
  {
    slug: "react-summit-2026",
    image: "/images/event3.png",
    title: "React Summit 2026",
    location: "Amsterdam, Netherlands",
    date: "January 20-21, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "ai-ml-summit-2026",
    image: "/images/event4.png",
    title: "AI & ML Summit 2026",
    location: "San Francisco, CA, USA",
    date: "February 11-13, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "jsconf-us-2026",
    image: "/images/event5.png",
    title: "JSConf US 2026",
    location: "Portland, OR, USA",
    date: "March 5-7, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "hack-the-planet-2026",
    image: "/images/event1.png",
    title: "Hack the Planet 2026",
    location: "New York, NY, USA",
    date: "March 20-21, 2026",
    time: "36 Hours",
  },
  {
    slug: "open-source-meetup-2026",
    image: "/images/event6.png",
    title: "London Open Source Meetup",
    location: "London, UK",
    date: "April 8, 2026",
    time: "6:30 PM - 9:00 PM",
  },
  {
    slug: "mobile-dev-summit-2026",
    image: "/images/event2.png",
    title: "Mobile Development Summit 2026",
    location: "Austin, TX, USA",
    date: "April 22, 2026",
    time: "9:30 AM - 5:30 PM",
  },
  {
    slug: "cybersecurity-forum-2026",
    image: "/images/event3.png",
    title: "Cybersecurity Forum 2026",
    location: "Toronto, Canada",
    date: "May 14-15, 2026",
    time: "8:30 AM - 5:00 PM",
  },
  {
    slug: "data-science-hackathon-2026",
    image: "/images/event4.png",
    title: "Data Science Hackathon 2026",
    location: "Boston, MA, USA",
    date: "June 5-7, 2026",
    time: "72 Hours",
  },
  {
    slug: "frontend-conf-2026",
    image: "/images/event5.png",
    title: "Frontend Conf 2026",
    location: "San Diego, CA, USA",
    date: "June 18, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "devops-cloud-expo-2026",
    image: "/images/event1.png",
    title: "DevOps & Cloud Expo 2026",
    location: "Seattle, WA, USA",
    date: "July 9-10, 2026",
    time: "9:00 AM - 5:00 PM",
  },
];